[pytest]

# ===== Markers =====
markers =
    smoke: smoke tests (critical UI flow)
    regression: full regression suite

# ===== Default pytest options =====
addopts =
    -v
    -s
#    -n 3
#    --dist=load
    --alluredir=allure-results
    --clean-alluredir

# ===== Warnings =====
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
    ignore::UserWarning
    ignore::RuntimeWarning